{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6170ca1a-cb0b-4fa9-8b3c-43a2e307dd84",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ===============================\n",
    "# 1. IMPORT LIBRARIES\n",
    "# ===============================\n",
    "import torch\n",
    "import ast\n",
    "import re\n",
    "import numpy as np\n",
    "from datasets import load_dataset, Dataset\n",
    "from transformers import (\n",
    "    AutoTokenizer,\n",
    "    AutoModelForTokenClassification,\n",
    "    TrainingArguments,\n",
    "    Trainer,\n",
    "    DataCollatorForTokenClassification\n",
    ")\n",
    "\n",
    "from seqeval.metrics import (\n",
    "    precision_score,\n",
    "    recall_score,\n",
    "    f1_score,\n",
    "    accuracy_score,\n",
    "    classification_report\n",
    ")\n",
    "\n",
    "# ===============================\n",
    "# 2. GPU CHECK\n",
    "# ===============================\n",
    "print(\"GPU Available:\", torch.cuda.is_available())\n",
    "if torch.cuda.is_available():\n",
    "    print(\"GPU:\", torch.cuda.get_device_name(0))\n",
    "\n",
    "# ===============================\n",
    "# 3. LOAD DATASET\n",
    "# ===============================\n",
    "dataset = load_dataset(\"Josephgflowers/Financial-NER-NLP\")\n",
    "data = dataset[\"train\"]\n",
    "\n",
    "print(\"Dataset Loaded!\")\n",
    "\n",
    "# ===============================\n",
    "# 4. CONVERT TO NER FORMAT\n",
    "# ===============================\n",
    "def convert_to_ner(data):\n",
    "    new_data = []\n",
    "\n",
    "    for item in data:\n",
    "        text = item[\"user\"]\n",
    "        words = text.split()\n",
    "        labels = [\"O\"] * len(words)\n",
    "\n",
    "        try:\n",
    "            entities = ast.literal_eval(item[\"assistant\"])\n",
    "\n",
    "            for label, values in entities.items():\n",
    "                for value in values:\n",
    "                    for match in re.finditer(re.escape(str(value)), text):\n",
    "                        entity_words = text[match.start():match.end()].split()\n",
    "\n",
    "                        for i in range(len(words)):\n",
    "                            if words[i:i+len(entity_words)] == entity_words:\n",
    "                                labels[i] = \"B-\" + label\n",
    "                                for j in range(1, len(entity_words)):\n",
    "                                    if i+j < len(labels):\n",
    "                                        labels[i+j] = \"I-\" + label\n",
    "        except:\n",
    "            continue\n",
    "\n",
    "        new_data.append({\n",
    "            \"tokens\": words,\n",
    "            \"ner_tags\": labels\n",
    "        })\n",
    "\n",
    "    return new_data\n",
    "\n",
    "\n",
    "ner_data = convert_to_ner(data)\n",
    "print(\"Converted to NER format!\")\n",
    "\n",
    "# ===============================\n",
    "# 5. CREATE DATASET\n",
    "# ===============================\n",
    "dataset = Dataset.from_list(ner_data)\n",
    "\n",
    "# 🔥 REDUCE DATASET (VERY IMPORTANT)\n",
    "dataset = dataset.shuffle(seed=42).select(range(50000))\n",
    "\n",
    "# ===============================\n",
    "# 6. LABEL MAPPING\n",
    "# ===============================\n",
    "label_list = sorted(list(set(tag for row in ner_data for tag in row[\"ner_tags\"])))\n",
    "\n",
    "label2id = {l: i for i, l in enumerate(label_list)}\n",
    "id2label = {i: l for l, i in label2id.items()}\n",
    "\n",
    "# ===============================\n",
    "# 7. TOKENIZER\n",
    "# ===============================\n",
    "tokenizer = AutoTokenizer.from_pretrained(\"bert-base-uncased\")\n",
    "\n",
    "# ===============================\n",
    "# 8. TOKENIZE + ALIGN LABELS\n",
    "# ===============================\n",
    "def tokenize_and_align_labels(example):\n",
    "    tokenized = tokenizer(\n",
    "        example[\"tokens\"],\n",
    "        truncation=True,\n",
    "        is_split_into_words=True,\n",
    "        padding=\"max_length\",\n",
    "        max_length=128\n",
    "    )\n",
    "\n",
    "    word_ids = tokenized.word_ids()\n",
    "    labels = []\n",
    "    prev_word = None\n",
    "\n",
    "    for word_id in word_ids:\n",
    "        if word_id is None:\n",
    "            labels.append(-100)\n",
    "        elif word_id != prev_word:\n",
    "            labels.append(label2id.get(example[\"ner_tags\"][word_id], 0))\n",
    "        else:\n",
    "            labels.append(-100)\n",
    "\n",
    "        prev_word = word_id\n",
    "\n",
    "    tokenized[\"labels\"] = labels\n",
    "    return tokenized\n",
    "\n",
    "\n",
    "dataset = dataset.map(\n",
    "    tokenize_and_align_labels,\n",
    "    remove_columns=[\"tokens\", \"ner_tags\"]\n",
    ")\n",
    "\n",
    "print(\"Tokenization Done!\")\n",
    "\n",
    "# ===============================\n",
    "# 9. TRAIN-TEST SPLIT\n",
    "# ===============================\n",
    "dataset = dataset.train_test_split(test_size=0.2)\n",
    "\n",
    "train_dataset = dataset[\"train\"]\n",
    "test_dataset  = dataset[\"test\"]\n",
    "\n",
    "# ===============================\n",
    "# 10. LOAD MODEL\n",
    "# ===============================\n",
    "model = AutoModelForTokenClassification.from_pretrained(\n",
    "    \"bert-base-uncased\",\n",
    "    num_labels=len(label_list),\n",
    "    id2label=id2label,\n",
    "    label2id=label2id\n",
    ")\n",
    "\n",
    "# ===============================\n",
    "# 11. DATA COLLATOR\n",
    "# ===============================\n",
    "data_collator = DataCollatorForTokenClassification(tokenizer)\n",
    "\n",
    "# ===============================\n",
    "# 12. METRICS\n",
    "# ===============================\n",
    "def compute_metrics(p):\n",
    "    predictions, labels = p\n",
    "    predictions = np.argmax(predictions, axis=2)\n",
    "\n",
    "    true_predictions = []\n",
    "    true_labels = []\n",
    "\n",
    "    for pred, lab in zip(predictions, labels):\n",
    "        pred_labels = []\n",
    "        true_lab = []\n",
    "\n",
    "        for p_, l_ in zip(pred, lab):\n",
    "            if l_ != -100:\n",
    "                pred_labels.append(id2label[p_])\n",
    "                true_lab.append(id2label[l_])\n",
    "\n",
    "        true_predictions.append(pred_labels)\n",
    "        true_labels.append(true_lab)\n",
    "\n",
    "    return {\n",
    "        \"accuracy\": accuracy_score(true_labels, true_predictions),\n",
    "        \"precision\": precision_score(true_labels, true_predictions),\n",
    "        \"recall\": recall_score(true_labels, true_predictions),\n",
    "        \"f1\": f1_score(true_labels, true_predictions),\n",
    "    }\n",
    "\n",
    "# ===============================\n",
    "# 13. TRAINING CONFIG\n",
    "# ===============================\n",
    "training_args = TrainingArguments(\n",
    "    output_dir=\"./results\",\n",
    "    learning_rate=3e-5,\n",
    "    per_device_train_batch_size=4,\n",
    "    per_device_eval_batch_size=4,\n",
    "    gradient_accumulation_steps=2,\n",
    "    num_train_epochs=3,\n",
    "    logging_steps=50,\n",
    "    eval_strategy=\"epoch\",       # ⚠️ for your version\n",
    "    save_strategy=\"epoch\",\n",
    "    bf16=True,                  # 🔥 best for RTX 50\n",
    "    dataloader_num_workers=2,\n",
    "    remove_unused_columns=False,\n",
    "    report_to=\"none\"\n",
    ")\n",
    "\n",
    "# ===============================\n",
    "# 14. TRAINER\n",
    "# ===============================\n",
    "trainer = Trainer(\n",
    "    model=model,\n",
    "    args=training_args,\n",
    "    train_dataset=train_dataset,\n",
    "    eval_dataset=test_dataset,\n",
    "    data_collator=data_collator,\n",
    "    compute_metrics=compute_metrics\n",
    ")\n",
    "\n",
    "# ===============================\n",
    "# 15. TRAIN 🚀\n",
    "# ===============================\n",
    "trainer.train()\n",
    "\n",
    "# ===============================\n",
    "# 16. EVALUATE\n",
    "# ===============================\n",
    "results = trainer.evaluate()\n",
    "\n",
    "print(\"\\n===== FINAL RESULTS =====\")\n",
    "for k, v in results.items():\n",
    "    print(f\"{k}: {v:.4f}\")\n",
    "\n",
    "# ===============================\n",
    "# 17. DETAILED REPORT\n",
    "# ===============================\n",
    "predictions, labels, _ = trainer.predict(test_dataset)\n",
    "predictions = np.argmax(predictions, axis=2)\n",
    "\n",
    "true_predictions = [\n",
    "    [id2label[p] for (p, l) in zip(pred, lab) if l != -100]\n",
    "    for pred, lab in zip(predictions, labels)\n",
    "]\n",
    "\n",
    "true_labels = [\n",
    "    [id2label[l] for (p, l) in zip(pred, lab) if l != -100]\n",
    "    for pred, lab in zip(predictions, labels)\n",
    "]\n",
    "\n",
    "print(\"\\n===== CLASSIFICATION REPORT =====\")\n",
    "print(classification_report(true_labels, true_predictions))\n",
    "\n",
    "# ===============================\n",
    "# 18. SAVE MODEL\n",
    "# ===============================\n",
    "trainer.save_model(\"financial_bert_ner\")\n",
    "tokenizer.save_pretrained(\"financial_bert_ner\")\n",
    "\n",
    "print(\"\\n✅ Model training complete & saved!\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:ner_gpu]",
   "language": "python",
   "name": "conda-env-ner_gpu-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
